export const siteConfig = {
  name: 'Luxusumzug',
  tagline: 'Umziehen mit Stil',
  legalName: 'Luxusumzug Wien',
  title: 'Luxusumzug Wien | Umziehen mit Stil, Sicherheit und Struktur',
  description:
    'Luxusumzug Wien: Ratgeber für hochwertige, sichere und stressfreie Übersiedlungen. Umzugsplanung, Möbeltransport, Kosten, Checklisten und VIP-Relocation in Österreich.',
  url: 'https://luxusumzug.at',
  locale: 'de-AT',
  ogLocale: 'de_AT',
  city: 'Wien',
  region: 'Wien',
  country: 'AT',
  ownerName: 'Nuran Duman',
  email: 'info@luxusumzug.at',
  ogImage: '/images/og-cover.jpg',
  twitterHandle: '@luxusumzug',
  keywords: [
    'Luxusumzug Wien',
    'Umzug Wien',
    'VIP Umzug',
    'Möbeltransport Wien',
    'Umzugsplanung',
    'Umzugskosten Wien',
    'Umzugscheckliste',
    'Kunsttransport Wien',
    'Relocation Wien',
    'Diplomaten Umzug Wien',
    'Weinkeller Umzug',
    'Smart Home Umzug',
  ],
} as const;

export const navItems = [
  { href: '/', label: 'Start' },
  { href: '/blog/', label: 'Ratgeber' },
  { href: '/umzugsplanung/', label: 'Umzugsplanung' },
  { href: '/moebeltransport/', label: 'Möbeltransport' },
  { href: '/kosten/', label: 'Kosten' },
  { href: '/checklisten/', label: 'Checklisten' },
  { href: '/ueber-uns/', label: 'Über uns' },
] as const;
